### ISSUE TITLE
xlsx package dependency issue though I have uninstalled from dependencies

### ISSUE THREAD

**Issue by vasudevaraopaila** [e965/sheetjs-npm-publisher#1]
To fix the snyk issue in mat table exporter package due to the xlsx dependency,I have published two packages to replacing mat table exporter and cdk table exporter(copied from these two and changed names), and added @e965/xlsx as a dependency for cdk table exporter. But the compilation is failing by throwing the below issues.

./node_modules/config-table-exporter/fesm2020/cdk-table-exporter.mjs:130:21-54 - Error: Module not found: Error: Can't resolve 'xlsx/dist/xlsx.mini.min' in 'D:\Projects\Config Hub\ba-configHub-UI\Config-Hub-Main\node_modules\config-table-exporter\fesm2020'

./node_modules/config-table-exporter/fesm2020/cdk-table-exporter.mjs:132:21-35 - Error: Module not found: Error: Can't resolve 'xlsx' in 'D:\Projects\Config Hub\ba-configHub-UI\Config-Hub-Main\node_modules\config-table-exporter\fesm2020'

Adding the packages below for reference
https://www.npmjs.com/package/config-mat-table-exporter?activeTab=code
https://www.npmjs.com/package/config-table-exporter?activeTab=code

**Comment by e965** [comment]
Given that there is a problem with the original package as well (if I understand you correctly), you should write to their issue tracker - https://git.sheetjs.com/sheetjs/sheetjs/issues
