### ISSUE TITLE
The latest versions of sheetjs.com and npm are different.

### ISSUE THREAD

**Issue by ohkwon79** [e965/sheetjs-npm-publisher#2]
The latest version currently announced on sheetjs.com is 0.20.1

The latest version of https://www.npmjs.com/package/@e965/xlsx is 0.20.2.

Wouldn't it be right to change the logic of publishing based on the latest version of the master branch to the logic of publishing based on the last tag version?

**Comment by e965** [comment]
> The latest version currently announced on sheetjs.com is 0.20.1

No, it's not: https://git.sheetjs.com/sheetjs/sheetjs/src/branch/master/package.json
![image](https://github.com/e965/sheetjs-npm-publisher/assets/18071040/f4b4016a-f9c6-415c-86eb-e046c71375c4)
Maybe they haven't had time to update the website pages to have the new version there yet

However, I understand what you're saying - this is indeed a potential problem. PRs are welcome

**Comment by ohkwon79** [comment]
yes. I will post a PR as soon as I have time.
