### ISSUE TITLE
publish date of v0.20.2 differs

### ISSUE THREAD

**Issue by marc-mabe** [e965/sheetjs-npm-publisher#4]
On sheetjs git I see the tag got created at 2024-04-05
-> https://git.sheetjs.com/sheetjs/sheetjs/tags
-> https://git.sheetjs.com/sheetjs/sheetjs/src/commit/a0bed2a97dcb1e3b76049be91abf3747f333c975

But your npm version 0.20.2 got created 2024-03-23 already
-> https://www.npmjs.com/package/@e965/xlsx/v/0.20.2

How can this be possible? Did they changed the tag?

**Comment by marc-mabe** [comment]
PS: Currently I have to decide what to do with this package ...
* Keep the vulnerable npm package
* Use Sheetjs CDN (but it they really changing existing tags ... ?)
* Use your (or an own version) of this project
* Copy into our own repo

What has the higher risk here?
How do I manage version upgrades in the future?
How do I know of new security vulnerabilities?

If every project would handle it like SheetJS we would need to pay a separate person just to manage JS dependencies of a **small** project with ~1200 packages :hankey: 

On working with strict security policies this would mean a complete rewrite to get rid of this nightmare :/

**Comment by e965** [comment]
This was because the project previously relied on the version from package.json - the sheetjs authors changed it before they actually released the new version

The project is now using the git tagged version (see https://github.com/e965/sheetjs-npm-publisher/pull/3), and this (supposedly) shouldn't happen anymore

**Comment by e965** [comment]
If it's important to you, I can manually make a new npm release (0.20.2-released maybe), but I think it's easier to wait until the new version is available

**Comment by e965** [comment]
Manually released version `0.20.2-released.0`
Unfortunately it won't have a provenance signature, but the next version should be fine
